### ISSUE TITLE
naivgation keys suddenly stop working

### ISSUE THREAD

**Issue by marti-toonen** [klembot/twinejs#1427] opened 2023-07-20 20:14 UTC
### Describe the bug.

Eventually as I'm typing I start to notice that the enter button stops giving me a line break. I can use the arrow keys to go side to side on a single line but not up or down, and the home/end keys do nothing. The cursor blinks as normal until I hit these buttons (home/end, up arrow/down arrow, enter on both the numpad and regular keyboard) where it freezes until I stop pressing it.

### Steps to reproduce:

I'm really not sure as it seems to happen at random. Some days I can create and fill several passages with no issue, whereas days like today the enter button will just suddenly stop working as I'm trying to finish up work on a single passage.

UPDATE: Issue seems to pop up when closing HTML tags for some reason? Like if I do a `<h1>stuff between, maybe particularly (link: "words")[actions and then navigation]</h1>` it'll suddenly stop working.

### Expected behavior:

Continued functionality of the navigation keys, especially the ability to use the enter key to create line breaks without which I can't work.

### Additional context on this problem.

Pressing the buttons after they've failed to function produces no error or warning in the debug console. Closing and reopening Twine, or returning to the Library and then hopping back into the file will temporarily allow me to use these keys again. Issue began upon updating to 2.7.0, and has happened across two separate devices (a Windows PC tower with a wireless keyboard and a Windows laptop with the regular laptop keyboard, both fully updated to the latest version of Windows and Twine). I can continue typing as normal, so the keyboard still functions. There is no indication after I have reopened a project that the program registered the keystrokes on the navigation keys at all (no extra white space from hitting enter several times) and the navigation keys haven't stopped on any other program.

I am using Harlowe, whose GitHub also does not seem to have this as a reported issue, so I'm starting here although it doesn't seem to be an issue here either 😅😅

### Twine version number

2.7.0

### Does this problem occur with the web version of Twine or the desktop app?

Desktop app

### What operating system does this problem occur on?

Windows

### If this problem is occurring with the web version of Twine, what browser does it occur on?

None

### Presubmission checklist

- [ ] I am interested in working on code that would fix this bug. (This is not required to submit a bug report.)
- [X] I have done a search and believe that an issue does not already exist for this bug in the GitHub repository.
- [X] If this problem is occurring with the app version of Twine, it still happens after I remove the `user.css` file from my Twine folder. (You would've added this file yourself. If you don't understand this question, you can safely check this box.)
- [X] I have read and agree to abide by this project's Code of Conduct.

**Comment by greyelf** [comment] 2023-07-20 23:31
Duplicate of #1425

**Closed** 2023-07-21 12:42 UTC
Labels: bug
